scripts: document usage

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -2,6 +2,15 @@
 
 set -o nounset -o noclobber -o pipefail
 
+fail() {
+    echo "$1" | grep --color=always . >&2 
+    exit 1
+}
+
+if [[ -z ${1:-} ]]; then
+    fail "usage: extract /path/to/archive"
+fi
+
 if [[ -f $1 ]] ; then
     case $1 in
         *.tar.bz2)   tar xjf "$1"     ;;
@@ -15,8 +24,8 @@ if [[ -f $1 ]] ; then
         *.zip)       unzip "$1"       ;;
         *.Z)         uncompress "$1"  ;;
         *.7z)        7z x "$1"        ;;
-        *)           echo "'$1' cannot be extracted via extract" ;;
+        *)           fail "'$1' cannot be extracted via extract" ;;
     esac
 else
-    echo "'$1' is not a valid file"
+    fail "'$1' is not a valid file"
 fi
